python parse_test_res.py output/imagenet/HaPrompt/vit_b16_few_shot_16shots --test-log
python parse_test_res.py output/caltech101/HaPrompt/vit_b16_few_shot_16shots --test-log
python parse_test_res.py output/oxford_pets/HaPrompt/vit_b16_few_shot_16shots --test-log
python parse_test_res.py output/stanford_cars/HaPrompt/vit_b16_few_shot_16shots --test-log
python parse_test_res.py output/oxford_flowers/HaPrompt/vit_b16_few_shot_16shots --test-log
python parse_test_res.py output/food101/HaPrompt/vit_b16_few_shot_16shots --test-log
python parse_test_res.py output/fgvc_aircraft/HaPrompt/vit_b16_few_shot_16shots --test-log
python parse_test_res.py output/sun397/HaPrompt/vit_b16_few_shot_16shots --test-log
python parse_test_res.py output/dtd/HaPrompt/vit_b16_few_shot_16shots --test-log
python parse_test_res.py output/eurosat/HaPrompt/vit_b16_few_shot_16shots --test-log
python parse_test_res.py output/ucf101/HaPrompt/vit_b16_few_shot_16shots --test-log